# Generated by Django 4.2.21 on 2025-05-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_searchhistory_delete_usersearchhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='client_id',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('client_id', 'city')},
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
    ]
