# Generated by Django 4.2.21 on 2025-05-27 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('weather', '0004_alter_searchhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['session_id', 'last_search'], name='weather_sea_session_204df8_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['city'], name='weather_sea_city_6eac89_idx'),
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='client_id',
        ),
    ]
